version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - run: pwd && cd interface && npm install && npm start
      - run: echo "buildando aplicação"
      
  test:
    docker:
      - image: cimg/node:14.19.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "Testando 1... 2... 3..."
      
workflows:
  sample:
    jobs:
      - build
      - test