version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install —-save-dev @testing-library/react-native
      - run: echo "buildando aplicação"
      - run:
          name: Install Dependencies
          command: cd interface && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      #- run: npm run Test

  test:
    docker:
      - image: cimg/node:14.19.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "Testando 1... 2... 3..."
      
workflows:
  sample:
    jobs:
      - build-and-test