version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - run: echo "buildando aplicação"
      - run:
          name: Instalar dependencias back
          command: cd backend && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "./backend/package-lock.json" }}
          paths:
            - ./backend/
      - run:
          name: Instalar dependencias front
          command: cd interface && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "./interface/package.json" }}
          paths:
            - ./interface/

      - run: echo "Aqui deveria testar..."
          
workflows:
  sample:
    jobs:
      - build-and-test