version: 2.1
orbs:
  node: circleci/node@4.7
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:14.19.0

    steps:
      - checkout
      - run: npm install 
      - run: echo "Buildando aplicação..."
  test:
    docker:
      - image: cimg/node:14.19.0
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Testando 1... 2... 3..."

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test