version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.19.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install —-save-dev @testing-library/react-native
      - run: echo "buildando aplicação"
      - run:
          name: Install Dependencies
          command: cd interface && npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./interface/
      #- run: npm run Test
      - run: echo "Aqui deveria testar..."
      
workflows:
  sample:
    jobs:
      - build-and-test